  [[main]]
  name = "Publications"
  identifier = "publications"
  weight = 300
  url = "/fr/publications"

  [[main]]
  name = "News"
  weight = 200
  identifier = "posts"
  url = "/fr/post/"

  [[main]]
  name = "A propos"
  weight = 100
  identifier = "about"
  url = "/fr"

  [[main]]
  name = "Code"
  weight = 400
  identifier = "code"
  url = "/fr/code/"

  [[main]]
  name = "Enseignments"
  weight = 500
  identifier = "teaching"
  url = "/fr/teaching/"